//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ebook
    {
        public int id { get; set; }
        public string ebook_id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string year { get; set; }
        public string describe { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> date_upload { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<int> countView { get; set; }
        public Nullable<int> countDowload { get; set; }
    
        public virtual Subject_Ebook Subject_Ebook { get; set; }
        public virtual User User { get; set; }
    }
}
