//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ebook> Ebooks { get; set; }
        public virtual DbSet<Essay> Essays { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subject_Ebook> Subject_Ebook { get; set; }
        public virtual DbSet<Subject_Essay> Subject_Essay { get; set; }
        public virtual DbSet<Subject_Thesis> Subject_Thesis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thesis> Theses { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
